species = [
  { name = "Antling", reroll = "Constitution" },
  { name = "Badgerling", reroll = "Strength" },
  { name = "Batling", reroll = "Wisdom" },
  { name = "Beetleling", reroll = "Strength" },
  { name = "Boarling", reroll = "Constitution" },
  { name = "Cricketling", reroll = "Strength" },
  { name = "Deerling", reroll = "Charisma" },
  { name = "Duckling", reroll = "Constitution" },
  { name = "Eelling", reroll = "Intelligence" },
  { name = "Elf", reroll = "Charisma" },
  { name = "Fishling", reroll = "Constitution" },
  { name = "Flealing", reroll = "Strength" },
  { name = "Flyling", reroll = "Dexterity" },
  { name = "Foxling", reroll = "Wisdom" },
  { name = "Frogling", reroll = "Charisma" },
  { name = "Gnome", reroll = "Intelligence" },
  { name = "Goatling", reroll = "Dexterity" },
  { name = "Goblin", reroll = "Dexterity" },
  { name = "Gooseling", reroll = "Constitution" },
  { name = "Hawkling", reroll = "Intelligence" },
  { name = "Hedgehogling", reroll = "Wisdom" },
  { name = "Houndling", reroll = "Charisma" },
  { name = "Human", reroll = "Any" },
  { name = "Magpieling", reroll = "Dexterity" },
  { name = "Moleling", reroll = "Intelligence" },
  { name = "Mothling", reroll = "Wisdom" },
  { name = "Mouseling", reroll = "Wisdom" },
  { name = "Newtling", reroll = "Charisma" },
  { name = "Owlling", reroll = "Wisdom" },
  { name = "Rabbitling", reroll = "Dexterity" },
  { name = "Ratling", reroll = "Intelligence" },
  { name = "Ravenling", reroll = "Charisma" },
  { name = "Slothling", reroll = "Strength" },
  { name = "Slugling", reroll = "Strength" },
  { name = "Sparrowling", reroll = "Wisdom" },
  { name = "Spiderling", reroll = "Dexterity" },
  { name = "Swanling", reroll = "Dexterity" },
  { name = "Toadling", reroll = "Strength" },
  { name = "Weaselling", reroll = "Strength" },
  { name = "Wormling", reroll = "Intelligence" },
]

classes = [
  { name = "Barbarian", has_md = false },
  { name = "Fighter", has_md = false },
  { name = "Hunter", has_md = false },
  { name = "Knight", has_md = false },
  { name = "Monk", has_md = false },
  { name = "Sorcerer", has_md = false },
  { name = "Summoner", has_md = false },
  { name = "Thief", has_md = false },
  { name = "Wizard", has_md = false },
]

wizard_archetypes = [
  { name = "Animist", school_type = "Outlawed" },
  { name = "Biomancer", school_type = "Outlawed" },
  { name = "Curse-Eater", school_type = "Outlawed" },
  { name = "Drowned", school_type = "Outsider" },
  { name = "Elementalist", school_type = "Chartered" },
  { name = "Elf", school_type = "Outsider" },
  { name = "Garden", school_type = "Chartered" },
  { name = "Geometer", school_type = "Chartered" },
  { name = "Illusionist", school_type = "Chartered" },
  { name = "Necromancer", school_type = "Outlawed" },
  { name = "Orthodox", school_type = "Chartered" },
  { name = "Spider", school_type = "Outsider" },
  { name = "White-Hand", school_type = "Chartered" },
]
